language: php
php:
  - 5.4

mysql:
  database: foodcoopsystem
  username: root

before_script:
  - pyrus channel-discover pear.drush.org
  - pyrus install drush/drush
  - phpenv rehash
  - drush dl --yes drupal
  - cd drupal-*
  - drush --yes si standard --db-url=mysql://root:@localhost/foodcoopsystem
  - drush cc all


