; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[drupal][version] = "7.36"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[advanced_forum][subdir] = "contrib"
projects[advanced_forum][version] = "2.5-rc1"

projects[boxes][subdir] = "contrib"
projects[boxes][version] = "1.2"

projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-rc1"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.8"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.0"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.6-rc1"

projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.10"

projects[commerce_custom_order_status][subdir] = "contrib"
projects[commerce_custom_order_status][version] = "1.0"

projects[commerce_custom_product][subdir] = "contrib"
projects[commerce_custom_product][version] = "1.0-beta2"

projects[commerce_flat_rate][subdir] = "contrib"
projects[commerce_flat_rate][version] = "1.0-beta2"

projects[commerce_product_bundle][subdir] = "contrib"
projects[commerce_product_bundle][version] = "1.0-alpha6"

projects[commerce_productpopularity][subdir] = "contrib"
projects[commerce_productpopularity][version] = "1.0-alpha1"

projects[commerce_add_to_cart_extras][download][type] = "git"
projects[commerce_add_to_cart_extras][download][url] = "http://git.drupal.org/project/commerce_add_to_cart_extras.git"
projects[commerce_add_to_cart_extras][download][branch] = "7.x-1.x"
projects[commerce_add_to_cart_extras][download][revision] = "c3d0ed2882508d6c97f62ee50a858a8bc3933ceb"
projects[commerce_add_to_cart_extras][subdir] = "contrib"

projects[commerce_autosku][subdir] = "contrib"
projects[commerce_autosku][version] = "1.1"

projects[calendar][subdir] = "contrib"
projects[calendar][version] = "3.5"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.16"

projects[drupalforfirebug][subdir] = "developer"
projects[drupalforfirebug][version] = "1.4"

projects[coder][subdir] = "developer"
projects[coder][version] = "1.2"

projects[devel][subdir] = "developer"
projects[devel][version] = "1.5"

projects[hacked][subdir] = "developer"
projects[hacked][version] = "2.0-beta5"

projects[performance][subdir] = "developer"
projects[performance][version] = "1.7"

projects[commerce_decimal_quantities][subdir] = "contrib"
projects[commerce_decimal_quantities][version] = "1.0"

projects[commerce_extra][patch][0] = "sites/all/modules/patch/commerce_extra_changes.patch"
projects[commerce_extra][subdir] = "contrib"
projects[commerce_extra][version] = "1.0-alpha1"

projects[commerce_features][subdir] = "contrib"
projects[commerce_features][version] = "1.0"

projects[commerce_reports][patch][0] = "sites/all/modules/patch/commerce_reports.module.patch"
projects[commerce_reports][subdir] = "contrib"
projects[commerce_reports][version] = "3.0-beta2"

projects[commerce_shipping][subdir] = "contrib"
projects[commerce_shipping][version] = "1.1"

projects[commerce_stock][subdir] = "contrib"
projects[commerce_stock][version] = "1.2"

projects[customer_profile_type_ui][subdir] = "contrib"
projects[customer_profile_type_ui][version] = "1.0"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[cookie_cache_bypass_adv][subdir] = "contrib"
projects[cookie_cache_bypass_adv][version] = "1.1"

projects[context][subdir] = "contrib"
projects[context][version] = "3.5"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9-beta2"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entitycache][subdir] = "contrib"
projects[entitycache][version] = "1.2"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.4"

projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"

projects[field_reference][subdir] = "contrib"
projects[field_reference][version] = "1.0"

projects[flag][subdir] = "contrib"
projects[flag][version] = "2.2"

projects[flag_limit][subdir] = "contrib"
projects[flag_limit][version] = "1.0-alpha1"

projects[jstimer][subdir] = "contrib"
projects[jstimer][version] = "1.3"

projects[fpa][subdir] = "contrib"
projects[fpa][version] = "2.6"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5"

projects[invite][subdir] = "contrib"
projects[invite][version] = "2.1-beta2"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[legal][subdir] = "contrib"
projects[legal][version] = "1.5"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "1.0"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.1"

projects[logintoboggan][subdir] = "contrib"
projects[logintoboggan][version] = "1.4"

projects[memcache][subdir] = "contrib"
projects[memcache][version] = "1.4-beta1"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[node_export][subdir] = "contrib"
projects[node_export][version] = "3.0"

projects[nodereference_url][subdir] = "contrib"
projects[nodereference_url][contrib] = "1.12"
projects[nodereference_url][version] = "1.12"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[print][subdir] = "contrib"
projects[print][version] = "1.3"

projects[quicktabs][patch][0] = "sites/all/modules/patch/quicktabs_styles.patch"
projects[quicktabs][subdir] = "contrib"
projects[quicktabs][version] = "3.6"

projects[role_expire][patch][0] = "sites/all/modules/patch/0001-Issue-1442936-by-MacMladen-Removes-call-by-reference.patch"
projects[role_expire][subdir] = "contrib"
projects[role_expire][version] = "1.0-beta2"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.7"

projects[rules_forms][subdir] = "contrib"
projects[rules_forms][version] = "1.0-rc2"

projects[uuid][subdir] = "contrib"
projects[uuid][download][type] = "git"
projects[uuid][download][url] = "http://git.drupal.org/project/uuid.git"
projects[uuid][download][revision] = "806c3011accaa93a835b6d0849b3dfde04c9e139"
projects[uuid][download][branch] = "7.x-1.x"
projects[uuid][version] = "1.0-alpha6"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[tagclouds][subdir] = "contrib"
projects[tagclouds][version] = "1.10"

projects[taxonomy_access][subdir] = "contrib"
projects[taxonomy_access][version] = "1.0-rc1"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][patch][0] = "sites/all/modules/patch/views_handler_field.inc.patch"
projects[views][subdir] = "contrib"
projects[views][version] = "3.8"

projects[views_pdf][subdir] = "contrib"
projects[views_pdf][version] = "1.4"

projects[rules_link][subdir] = "contrib"
projects[rules_link][version] = "1.1"

projects[views_calc][subdir] = "contrib"
projects[views_calc][version] = "1.1"

projects[views_php][download][type] = "git"
projects[views_php][download][url] = "http://git.drupal.org/project/views_php.git"
projects[views_php][download][branch] = "7.x-1.x"
projects[views_php][download][revision] = "2b5ed52228394ee3c8e8c86be283da957cdfa6f6"
projects[views_php][subdir] = "contrib"
projects[views_php][version] = "1.0-alpha1"

projects[visualization][subdir] = "contrib"
projects[visualization][version] = "1.0-alpha1"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.21"

projects[webform_conditional][subdir] = "contrib"
projects[webform_conditional][version] = "1.0-beta2"

projects[webform_rules][subdir] = "contrib"
projects[webform_rules][version] = "1.6"

projects[webform_validation][subdir] = "contrib"
projects[webform_validation][version] = "1.7"

projects[framework][version] = "3.6"

; Libraries
libraries[firephpcore][download][type] = "get"
libraries[firephpcore][download][url] = "https://github.com/firephp/firephp-core/archive/v0.3.2.zip"
libraries[firephpcore][download][subtree] = "/firephp-core-0.3.2/packages/core/"
libraries[firephpcore][directory_name] = "FirePHPCore/FirePHPCore"
libraries[firephpcore][type] = "library"

libraries[fpdi][download][type] = "get"
libraries[fpdi][download][url] = "http://www.setasign.com/supra/kon2_dl/39034/FPDI-1.4.2.zip"
libraries[fpdi][directory_name] = "fpdi"
libraries[fpdi][type] = "library"

libraries[tcpdf][download][type] = "git"
libraries[tcpdf][download][url] = "git://git.code.sf.net/p/tcpdf/code"
libraries[tcpdf][download][tag] = "6.0.088"
libraries[tcpdf][directory_name] = "tcpdf"
libraries[tcpdf][type] = "library"

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.0.2/ckeditor_4.0.2_standard.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][destination] = "libraries"
