<?php
/**
 * @file
 * object_export_test.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function object_export_test_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'vid\' => \'18\',
      \'uid\' => \'1\',
      \'title\' => \'Tura 07.09.2012 - 25.09.2012\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'1\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'1422890f-a830-b844-8131-57c59381e0ca\',
      \'nid\' => \'18\',
      \'type\' => \'tura\',
      \'language\' => \'pl\',
      \'created\' => \'1346752485\',
      \'changed\' => \'1346752485\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'618f35cd-886b-c2f4-a5f5-0521e5e60de0\',
      \'revision_timestamp\' => \'1346752485\',
      \'revision_uid\' => \'1\',
      \'body\' => array(),
      \'field_poczatek\' => array(),
      \'field_dostawca\' => array(),
      \'name\' => \'ObinMaster\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:34:"user_relationships_ui_auto_approve";a:0:{}}\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'19\',
      \'uid\' => \'1\',
      \'title\' => \'Tura 04-07.09.2012\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'1\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'3036df77-fbd9-4ae4-a969-421472c83a27\',
      \'nid\' => \'19\',
      \'type\' => \'tura\',
      \'language\' => \'pl\',
      \'created\' => \'1346752641\',
      \'changed\' => \'1346759726\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'80c8d644-7aea-e0d4-017f-dd6bf790ed87\',
      \'revision_timestamp\' => \'1346759726\',
      \'revision_uid\' => \'1\',
      \'body\' => array(),
      \'field_poczatek\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2012-09-03 10:00:00\',
            \'value2\' => \'2012-09-07 10:00:00\',
            \'timezone\' => \'Europe/Berlin\',
            \'timezone_db\' => \'UTC\',
            \'date_type\' => \'datetime\',
            \'db\' => array(
              \'value\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-03T10:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-03T10:00:00+00:00\',
                 \'date\' => \'2012-09-03 10:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
              \'value2\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-07T10:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-07T10:00:00+00:00\',
                 \'date\' => \'2012-09-07 10:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
            ),
          ),
        ),
      ),
      \'field_dostawca\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'6\',
          ),
        ),
      ),
      \'name\' => \'ObinMaster\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:34:"user_relationships_ui_auto_approve";a:0:{}}\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'23\',
      \'uid\' => \'1\',
      \'title\' => \'Koordynator/koordynatorka\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'1\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'8111da5e-d0e3-47f4-cd8b-51a0461c4308\',
      \'nid\' => \'23\',
      \'type\' => \'koordynacja\',
      \'language\' => \'pl\',
      \'created\' => \'1346756100\',
      \'changed\' => \'1346756100\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'84daa3fb-e2b8-9474-c9ed-db2f4fb1b8a7\',
      \'revision_timestamp\' => \'1346756100\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Koordynator musi mieć doświadczenie, druga zgłoszona osoba to asystent\',
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p>Koordynator musi mieć doświadczenie, druga zgłoszona osoba to asystent</p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'field_tura\' => array(
        \'und\' => array(
          array(
            \'nid\' => \'19\',
          ),
        ),
      ),
      \'field_poczatek\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2012-09-04 11:00:00\',
            \'value2\' => \'2012-09-07 11:00:00\',
            \'timezone\' => \'Europe/Berlin\',
            \'timezone_db\' => \'UTC\',
            \'date_type\' => \'datetime\',
            \'db\' => array(
              \'value\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-04T11:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-04T11:00:00+00:00\',
                 \'date\' => \'2012-09-04 11:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
              \'value2\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-07T11:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-07T11:00:00+00:00\',
                 \'date\' => \'2012-09-07 11:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
            ),
          ),
        ),
      ),
      \'field_zgloszeni\' => array(),
      \'field_otwarte_zgloszenia\' => array(),
      \'name\' => \'ObinMaster\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:34:"user_relationships_ui_auto_approve";a:0:{}}\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'22\',
      \'uid\' => \'1\',
      \'title\' => \'Kjasjer/kasjerka\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'1\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'efe2c1d6-5d44-5934-01c3-d88a51e023db\',
      \'nid\' => \'22\',
      \'type\' => \'kasjer\',
      \'language\' => \'pl\',
      \'created\' => \'1346756011\',
      \'changed\' => \'1346756011\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'893ee7d8-5e1d-3b34-d54a-e37571000ca6\',
      \'revision_timestamp\' => \'1346756011\',
      \'revision_uid\' => \'1\',
      \'body\' => array(),
      \'field_zgloszeni\' => array(),
      \'field_tura\' => array(
        \'und\' => array(
          array(
            \'nid\' => \'19\',
          ),
        ),
      ),
      \'field_poczatek\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2012-09-04 11:00:00\',
            \'value2\' => \'2012-09-07 11:00:00\',
            \'timezone\' => \'Europe/Berlin\',
            \'timezone_db\' => \'UTC\',
            \'date_type\' => \'datetime\',
            \'db\' => array(
              \'value\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-04T11:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-04T11:00:00+00:00\',
                 \'date\' => \'2012-09-04 11:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
              \'value2\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-07T11:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-07T11:00:00+00:00\',
                 \'date\' => \'2012-09-07 11:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
            ),
          ),
        ),
      ),
      \'field_otwarte_zgloszenia\' => array(),
      \'name\' => \'ObinMaster\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:34:"user_relationships_ui_auto_approve";a:0:{}}\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'24\',
      \'uid\' => \'1\',
      \'title\' => \'Nadzur księgowości\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'1\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'0403165f-65d6-3b04-b94d-d92afd577806\',
      \'nid\' => \'24\',
      \'type\' => \'nadz_r_ksi_gowo_ci\',
      \'language\' => \'pl\',
      \'created\' => \'1346756132\',
      \'changed\' => \'1346756132\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'e23cd4b9-12cd-02b4-8556-a56c91b444ba\',
      \'revision_timestamp\' => \'1346756132\',
      \'revision_uid\' => \'1\',
      \'body\' => array(),
      \'field_tura\' => array(
        \'und\' => array(
          array(
            \'nid\' => \'19\',
          ),
        ),
      ),
      \'field_poczatek\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2012-09-04 11:00:00\',
            \'value2\' => \'2012-09-07 11:00:00\',
            \'timezone\' => \'Europe/Berlin\',
            \'timezone_db\' => \'UTC\',
            \'date_type\' => \'datetime\',
            \'db\' => array(
              \'value\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-04T11:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-04T11:00:00+00:00\',
                 \'date\' => \'2012-09-04 11:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
              \'value2\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-07T11:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-07T11:00:00+00:00\',
                 \'date\' => \'2012-09-07 11:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
            ),
          ),
        ),
      ),
      \'field_zgloszeni\' => array(),
      \'field_otwarte_zgloszenia\' => array(),
      \'name\' => \'ObinMaster\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:34:"user_relationships_ui_auto_approve";a:0:{}}\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'20\',
      \'uid\' => \'1\',
      \'title\' => \'Ważący\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'1\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'28f67522-631b-fe74-2589-76543adf4e6f\',
      \'nid\' => \'20\',
      \'type\' => \'wazacy\',
      \'language\' => \'pl\',
      \'created\' => \'1346752769\',
      \'changed\' => \'1346754136\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'f410b7b6-c6d1-aa04-a515-ee19be187b2f\',
      \'revision_timestamp\' => \'1346754136\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Jedne lub dwóch ważących\',
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p>Jedne lub dwóch ważących</p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'field_poczatek\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2012-09-04 10:00:00\',
            \'value2\' => \'2012-09-12 10:00:00\',
            \'timezone\' => \'Europe/Berlin\',
            \'timezone_db\' => \'UTC\',
            \'date_type\' => \'datetime\',
            \'db\' => array(
              \'value\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-04T10:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-04T10:00:00+00:00\',
                 \'date\' => \'2012-09-04 10:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
              \'value2\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-12T10:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-12T10:00:00+00:00\',
                 \'date\' => \'2012-09-12 10:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
            ),
          ),
        ),
      ),
      \'field_tura\' => array(
        \'und\' => array(
          array(
            \'nid\' => \'19\',
          ),
        ),
      ),
      \'field_zgloszeni\' => array(),
      \'field_otwarte_zgloszenia\' => array(),
      \'name\' => \'ObinMaster\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:34:"user_relationships_ui_auto_approve";a:0:{}}\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'25\',
      \'uid\' => \'1\',
      \'title\' => \'Sprzątanie\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'1\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'dad3bfa6-bf8e-3c34-b549-b81b4a99b1df\',
      \'nid\' => \'25\',
      \'type\' => \'sprz_tanie\',
      \'language\' => \'pl\',
      \'created\' => \'1346756185\',
      \'changed\' => \'1346756185\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'f7b3bf65-e51d-bcc4-eddb-aa06ce010377\',
      \'revision_timestamp\' => \'1346756185\',
      \'revision_uid\' => \'1\',
      \'body\' => array(),
      \'field_tura\' => array(
        \'und\' => array(
          array(
            \'nid\' => \'19\',
          ),
        ),
      ),
      \'field_poczatek\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2012-09-04 11:00:00\',
            \'value2\' => \'2012-09-07 11:00:00\',
            \'timezone\' => \'Europe/Berlin\',
            \'timezone_db\' => \'UTC\',
            \'date_type\' => \'datetime\',
            \'db\' => array(
              \'value\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-04T11:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-04T11:00:00+00:00\',
                 \'date\' => \'2012-09-04 11:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
              \'value2\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-07T11:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-07T11:00:00+00:00\',
                 \'date\' => \'2012-09-07 11:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
            ),
          ),
        ),
      ),
      \'field_zgloszeni\' => array(),
      \'field_otwarte_zgloszenia\' => array(),
      \'name\' => \'ObinMaster\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:34:"user_relationships_ui_auto_approve";a:0:{}}\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
  (object) array(
      \'vid\' => \'21\',
      \'uid\' => \'1\',
      \'title\' => \'Transport i zakupy\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'0\',
      \'promote\' => \'1\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'dfefd3f7-5878-28e4-75ff-bbb6dc754e14\',
      \'nid\' => \'21\',
      \'type\' => \'transport\',
      \'language\' => \'pl\',
      \'created\' => \'1346753351\',
      \'changed\' => \'1346756243\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'fc906d7b-05dc-41b4-65d4-d955bceaf062\',
      \'revision_timestamp\' => \'1346756243\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Potrzebny kierowca i pomocnik\',
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p>Potrzebny kierowca i pomocnik</p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'field_tura\' => array(
        \'und\' => array(
          array(
            \'nid\' => \'19\',
          ),
        ),
      ),
      \'field_poczatek\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2012-09-04 10:00:00\',
            \'value2\' => \'2012-09-07 10:00:00\',
            \'timezone\' => \'Europe/Berlin\',
            \'timezone_db\' => \'UTC\',
            \'date_type\' => \'datetime\',
            \'db\' => array(
              \'value\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-04T10:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-04T10:00:00+00:00\',
                 \'date\' => \'2012-09-04 10:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
              \'value2\' => DateObject::__set_state(array(
                 \'granularity\' => 
                array (
                  0 => \'year\',
                  1 => \'month\',
                  2 => \'day\',
                  3 => \'hour\',
                  4 => \'minute\',
                  5 => \'second\',
                  6 => \'timezone\',
                ),
                 \'errors\' => 
                array (
                ),
                 \'serializedTime\' => \'2012-09-07T10:00:00+00:00\',
                 \'serializedTimezone\' => \'UTC\',
                 \'timeOnly\' => false,
                 \'dateOnly\' => false,
                 \'originalTime\' => \'2012-09-07T10:00:00+00:00\',
                 \'date\' => \'2012-09-07 10:00:00\',
                 \'timezone_type\' => 3,
                 \'timezone\' => \'UTC\',
              )),
            ),
          ),
        ),
      ),
      \'field_zgloszeni\' => array(),
      \'field_otwarte_zgloszenia\' => array(),
      \'name\' => \'ObinMaster\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:34:"user_relationships_ui_auto_approve";a:0:{}}\',
      \'path\' => FALSE,
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
)',
);
  return $node_export;
}
