<?php

/**
 * Implements hook_views_api().
 */
function commerce_add_to_cart_extras_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_form_alter().
 *
 * If this is a Views Form (determined by $form_id) that contains this module's
 * quantity handler, alter the label of the submit button to "Add to cart".
 */
function commerce_add_to_cart_extras_form_alter(&$form, &$form_state, $form_id) {
  $is_quantity_form = FALSE;
  if (strpos($form_id, 'views_form_') === 0) {
    $view = $form_state['build_info']['args'][0];
    foreach ($view->field as $field) {
      if ($field instanceof commerce_add_to_cart_extras_handler_field_quantity) {
        $is_quantity_form = TRUE;
      }
    }
    // Allow form to work when embedded using views_embed_view(), or in a block.
    if (empty($view->override_path)) {
      if (!empty($view->preview) || $view->display_handler instanceof views_plugin_display_block) {
        $view->override_path = $_GET['q'];
        $query = drupal_get_query_parameters($_GET, array('q'));
        $form['#action'] = url($view->get_url(), array('query' => $query));
      }
    }
  }

  if ($is_quantity_form) {
    $form['actions']['submit']['#value'] = t('Add to cart');
  }
}
